# nb009
use_cosine: true
is_single: false
cv_debug: false
unique_key: "pub_title"
use_pprocess: false

# src/bridge.py
train: true
max_len: 128
tags_vals: "o o-dataset pad" # string w/ space delimiter
use_pos: false
debug: true
text_len: 15000 # 0 if not truncate

# localnb001 or localnb002
train_batch_size: 32
valid_batch_size: 64
epochs: 10
learning_rate: 2.0e-05
embedding_dim: 100

# kagglenb004
test_batch_size: 64
