# nb009
use_cosine: false
is_single: false

# src/bridge.py
train: true
max_len: 200 #290
tags_vals: "o o-dataset pad" # string w/ space delimiter
#gettext: false
use_pos: false
#cv: true
debug: true
text_len: 3000 #0 if not truncate

# localnb001
train_batch_size: 32
valid_batch_size: 16
epochs: 5
learning_rate: 2.0e-05

# kagglenb004
test_batch_size: 128
