# nb009
use_cosine: false
is_single: false

# src/bridge.py
train: true
max_len: 512
tags_vals: "o o-dataset pad" # string w/ space delimiter
use_pos: false
debug: true
text_len: 3000 # 0 if not truncate

# localnb001
train_batch_size: 8
valid_batch_size: 4
epochs: 5
learning_rate: 2.0e-05

# kagglenb004
test_batch_size: 1
